### Task 1 : Exploratory Data Analysis

##### Step A : Data Sourcing & Loading

Our datasets were obtained from two CSV files which contained the outcome of an online Stackoverflow survey that was completed by many programmers from different parts of the world in 2020. The CSV files were downloaded from Kaggle.com, a public data source.

In [1]:
#Import pandas library so as to read or load the primary dataset
import pandas as pd

#Read the primary dataset, which is the CSV file with a larger size as can be seen in the source folder
pry_df = pd.read_csv('C:/Users/hp/Downloads/Hamoye/Premier Project/developer_survey_2020/survey_results_public.csv')

In [2]:
#View the primary dataset
pry_df

Respondent                                         MainBranch Hobbyist  \
0               1                     I am a developer by profession      Yes   
1               2                     I am a developer by profession       No   
2               3                        I code primarily as a hobby      Yes   
3               4                     I am a developer by profession      Yes   
4               5  I used to be a developer by profession, but no...      Yes   
...           ...                                                ...      ...   
64456       64858                                                NaN      Yes   
64457       64867                                                NaN      Yes   
64458       64898                                                NaN      Yes   
64459       64925                                                NaN      Yes   
64460       65112                                                NaN      Yes   

        Age Age1stCode CompFreq  CompTotal  ConvertedComp             Country  \
0       NaN         13  Monthly        NaN            NaN             Germany   
1       NaN         19      NaN        NaN            NaN      United Kingdom   
2       NaN         15      NaN        NaN            NaN  Russian Federation   
3      25.0         18      NaN        NaN            NaN             Albania   
4      31.0         16      NaN        NaN            NaN       United States   
...     ...        ...      ...        ...            ...                 ...   
64456   NaN         16      NaN        NaN            NaN       United States   
64457   NaN        NaN      NaN        NaN            NaN             Morocco   
64458   NaN        NaN      NaN        NaN            NaN            Viet Nam   
64459   NaN        NaN      NaN        NaN            NaN              Poland   
64460   NaN        NaN      NaN        NaN            NaN               Spain   

         CurrencyDesc  ...                  SurveyEase           SurveyLength  \
0       European Euro  ...  Neither easy nor difficult  Appropriate in length   
1      Pound sterling  ...                         NaN                    NaN   
2                 NaN  ...  Neither easy nor difficult  Appropriate in length   
3        Albanian lek  ...                         NaN                    NaN   
4                 NaN  ...                        Easy              Too short   
...               ...  ...                         ...                    ...   
64456             NaN  ...                         NaN                    NaN   
64457             NaN  ...                         NaN                    NaN   
64458             NaN  ...                         NaN                    NaN   
64459             NaN  ...                         NaN                    NaN   
64460             NaN  ...                         NaN                    NaN   

      Trans                                     UndergradMajor  \
0        No  Computer science, computer engineering, or sof...   
1       NaN  Computer science, computer engineering, or sof...   
2       NaN                                                NaN   
3        No  Computer science, computer engineering, or sof...   
4        No  Computer science, computer engineering, or sof...   
...     ...                                                ...   
64456   NaN  Computer science, computer engineering, or sof...   
64457   NaN                                                NaN   
64458   NaN                                                NaN   
64459   NaN                                                NaN   
64460   NaN  Computer science, computer engineering, or sof...   

            WebframeDesireNextYear                      WebframeWorkedWith  \
0                     ASP.NET Core                    ASP.NET;ASP.NET Core   
1                              NaN                                     NaN   
2                              NaN                           

From the table immediately above, we can see that there were 64,461 respondents and each respondent was asked a total of 60 questions (if we ignore the "Respondent" column).

In [3]:
#Confirm that none of the respondents completed or was allowed to complete the survey more than once
print(pry_df.duplicated().sum())

0


In [4]:
#View the summary of statistics of the primary dataset

#View the summary with respect to numerical columns
pry_df.describe()

Respondent           Age      CompTotal  ConvertedComp   WorkWeekHrs
count  64461.000000  45446.000000   3.482600e+04   3.475600e+04  41151.000000
mean   32554.079738     30.834111  3.190464e+242   1.037561e+05     40.782174
std    18967.442360      9.585392            inf   2.268853e+05     17.816383
min        1.000000      1.000000   0.000000e+00   0.000000e+00      1.000000
25%    16116.000000     24.000000   2.000000e+04   2.464800e+04     40.000000
50%    32231.000000     29.000000   6.300000e+04   5.404900e+04     40.000000
75%    49142.000000     35.000000   1.250000e+05   9.500000e+04     44.000000
max    65639.000000    279.000000  1.111111e+247   2.000000e+06    475.000000

In [5]:
#View the summary with respect to all columns, numeric and mixed
pry_df.describe(include='all')

Respondent                      MainBranch Hobbyist           Age  \
count   64461.000000                           64162    64416  45446.000000   
unique           NaN                               5        2           NaN   
top              NaN  I am a developer by profession      Yes           NaN   
freq             NaN                           47193    50388           NaN   
mean    32554.079738                             NaN      NaN     30.834111   
std     18967.442360                             NaN      NaN      9.585392   
min         1.000000                             NaN      NaN      1.000000   
25%     16116.000000                             NaN      NaN     24.000000   
50%     32231.000000                             NaN      NaN     29.000000   
75%     49142.000000                             NaN      NaN     35.000000   
max     65639.000000                             NaN      NaN    279.000000   

       Age1stCode CompFreq      CompTotal  ConvertedComp        Country  \
count       57900    40069   3.482600e+04   3.475600e+04          64072   
unique         63        3            NaN            NaN            183   
top            15   Yearly            NaN            NaN  United States   
freq         5618    19818            NaN            NaN          12469   
mean          NaN      NaN  3.190464e+242   1.037561e+05            NaN   
std           NaN      NaN            inf   2.268853e+05            NaN   
min           NaN      NaN   0.000000e+00   0.000000e+00            NaN   
25%           NaN      NaN   2.000000e+04   2.464800e+04            NaN   
50%           NaN      NaN   6.300000e+04   5.404900e+04            NaN   
75%           NaN      NaN   1.250000e+05   9.500000e+04            NaN   
max           NaN      NaN  1.111111e+247   2.000000e+06            NaN   

                CurrencyDesc  ... SurveyEase           SurveyLength  Trans  \
count                  45472  ...      51802                  51701  49345   
unique                   142  ...          3                      3      2   
top     United States dollar  ...       Easy  Appropriate in length     No   
freq                   11050  ...      34626                  38769  48871   
mean                     NaN  ...        NaN                    NaN    NaN   
std                      NaN  ...        NaN                    NaN    NaN   
min                      NaN  ...        NaN                    NaN    NaN   
25%                      NaN  ...        NaN                    NaN    NaN   
50%                      NaN  ...        NaN                    NaN    NaN   
75%                      NaN  ...        NaN                    NaN    NaN   
max                      NaN  ...        NaN                    NaN    NaN   

                                           UndergradMajor  \
count                                               50995   
unique                                                 12   
top     Computer science, computer engineering, or sof...   
freq                                                31582   
mean                                                  NaN   
std                                                   NaN   
min                                                   NaN   
25%                                                   NaN   
50%                                                   NaN   
75%                                                   NaN   
max                                                   NaN   

       WebframeDesireNextYear WebframeWorkedWith  \
count                   40024              42279   
unique                   3986               3789   
top                  React.js             jQuery   
freq                     2480               2079   
mean                      NaN                NaN   
std                       NaN                NaN   
min                       NaN                NaN   
25%                       NaN                NaN   
50%                   

In [6]:
#View the all the column headers which actually contain all the questions
pry_df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'Age', 'Age1stCode', 'CompFreq',
       'CompTotal', 'ConvertedComp', 'Country', 'CurrencyDesc',
       'CurrencySymbol', 'DatabaseDesireNextYear', 'DatabaseWorkedWith',
       'DevType', 'EdLevel', 'Employment', 'Ethnicity', 'Gender', 'JobFactors',
       'JobSat', 'JobSeek', 'LanguageDesireNextYear', 'LanguageWorkedWith',
       'MiscTechDesireNextYear', 'MiscTechWorkedWith',
       'NEWCollabToolsDesireNextYear', 'NEWCollabToolsWorkedWith', 'NEWDevOps',
       'NEWDevOpsImpt', 'NEWEdImpt', 'NEWJobHunt', 'NEWJobHuntResearch',
       'NEWLearn', 'NEWOffTopic', 'NEWOnboardGood', 'NEWOtherComms',
       'NEWOvertime', 'NEWPurchaseResearch', 'NEWPurpleLink', 'NEWSOSites',
       'NEWStuck', 'OpSys', 'OrgSize', 'PlatformDesireNextYear',
       'PlatformWorkedWith', 'PurchaseWhat', 'Sexuality', 'SOAccount',
       'SOComm', 'SOPartFreq', 'SOVisitFreq', 'SurveyEase', 'SurveyLength',
       'Trans', 'UndergradMajor', 'WebframeDesireNextYear',
  

From the table immediately above, we can see that most of the column headers or questions were abbreviated. Therefore, we will check the dataset in the other CSV file to see if there are details there.

In [7]:
#Read the secondary dataset from the other CSV file
sec_df = pd.read_csv('C:/Users/hp/Downloads/Hamoye/Premier Project/developer_survey_2020/survey_results_schema.csv')

#View the secondary dataset
sec_df

Column                                       QuestionText
0           Respondent  Randomized respondent ID number (not in order ...
1           MainBranch  Which of the following options best describes ...
2             Hobbyist                            Do you code as a hobby?
3                  Age  What is your age (in years)? If you prefer not...
4           Age1stCode  At what age did you write your first line of c...
..                 ...                                                ...
56  WebframeWorkedWith  Which web frameworks have you done extensive d...
57       WelcomeChange  Compared to last year, how welcome do you feel...
58         WorkWeekHrs  On average, how many hours per week do you wor...
59           YearsCode  Including any education, how many years have y...
60        YearsCodePro  NOT including education, how many years have y...

[61 rows x 2 columns]

As expected, the other file contains details of the Questions. From the table immediately above, we can see that "Column" contains all the column headers in the primary dataset and "QuestionText" contains the details (or explanation) of all the abbreviated column headers.

In [8]:
#View details of any abbreviated column header or question
#For instance, to view details of NEWEdImpt, re-read the file as col_sec_df
col_sec_df = pd.read_csv('C:/Users/hp/Downloads/Hamoye/Premier Project/developer_survey_2020/survey_results_schema.csv', index_col='Column').QuestionText

#View the details of NEWEdImpt
col_sec_df['NEWEdImpt']

'How important is a formal education, such as a university degree in computer science, to your career?'

##### Step B : Data Cleaning

We will now obtain an insight into "Who the programmers (or respondents) are", "What they do" and "Where they come from".

In [9]:
#Choose the columns you need for your analysis
columns_used = [
    # Who they are 
    'Respondent','MainBranch','Gender','Ethnicity','EdLevel','Age','UndergradMajor',
    #What they do 
    'Hobbyist','Age1stCode','ConvertedComp','WebframeWorkedWith','WorkWeekHrs','DatabaseWorkedWith','DevType','Employment','JobFactors','LanguageWorkedWith','YearsCode','YearsCodePro',
    #Where do they come from 
    'Country'
]

In [10]:
#Check the total length or number of columns
len(columns_used)

20

In [11]:
#Create a new dataset containing only the necessary columns from the primary dataset
new_pry_df = pry_df[columns_used].copy()

In [12]:
#View the new dataset to confirm its properties
new_pry_df

Respondent                                         MainBranch Gender  \
0               1                     I am a developer by profession    Man   
1               2                     I am a developer by profession    NaN   
2               3                        I code primarily as a hobby    NaN   
3               4                     I am a developer by profession    Man   
4               5  I used to be a developer by profession, but no...    Man   
...           ...                                                ...    ...   
64456       64858                                                NaN    NaN   
64457       64867                                                NaN    NaN   
64458       64898                                                NaN    NaN   
64459       64925                                                NaN    NaN   
64460       65112                                                NaN    NaN   

                          Ethnicity  \
0      White or of European descent   
1                               NaN   
2                               NaN   
3      White or of European descent   
4      White or of European descent   
...                             ...   
64456                           NaN   
64457                           NaN   
64458                           NaN   
64459                           NaN   
64460                           NaN   

                                               EdLevel   Age  \
0      Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   NaN   
1         Bachelor’s degree (B.A., B.S., B.Eng., etc.)   NaN   
2                                                  NaN   NaN   
3      Master’s degree (M.A., M.S., M.Eng., MBA, etc.)  25.0   
4         Bachelor’s degree (B.A., B.S., B.Eng., etc.)  31.0   
...                                                ...   ...   
64456  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   NaN   
64457                                              NaN   NaN   
64458                        Primary/elementary school   NaN   
64459                                              NaN   NaN   
64460       Other doctoral degree (Ph.D., Ed.D., etc.)   NaN   

                                          UndergradMajor Hobbyist Age1stCode  \
0      Computer science, computer engineering, or sof...      Yes         13   
1      Computer science, computer engineering, or sof...       No         19   
2                                                    NaN      Yes         15   
3      Computer science, computer engineering, or sof...      Yes         18   
4      Computer science, computer engineering, or sof...      Yes         16   
...                                                  ...      ...        ...   
64456  Computer science, computer engineering, or sof...      Yes         16   
64457                                                NaN      Yes        NaN   
64458                                                NaN      Yes        NaN   
64459                                                NaN      Yes        NaN   
64460  Computer science, computer engineering, or sof...      Yes        NaN   

       ConvertedComp                      WebframeWorkedWith  WorkWeekHrs  \
0                NaN                    ASP.NET;ASP.NET Core         50.0   
1                NaN                                     NaN          NaN   
2                NaN                                     NaN          NaN   
3                NaN                                     NaN         40.0   
4                NaN                           Ruby on Rails          NaN   
...              ...                                     ...          ...   
64456            NaN                                     NaN          NaN   
64457            NaN                                     NaN          NaN   
64458            NaN                                     NaN          NaN   
64459            NaN                                     NaN          NaN   
64460       

We can see from the table immediately above that the new dataset contains the expected features and the number of rows and columns are complete.

In [13]:
#Create a new dataset containing only the necessary columns from the modified version of the secondary dataset i.e. col_sec_df
new_sec_df = col_sec_df[columns_used]

In [14]:
#View the new dataset that was obtained from the modified version of the secondary dataset
new_sec_df

Column
Respondent            Randomized respondent ID number (not in order ...
MainBranch            Which of the following options best describes ...
Gender                Which of the following describe you, if any? P...
Ethnicity             Which of the following describe you, if any? P...
EdLevel               Which of the following best describes the high...
Age                   What is your age (in years)? If you prefer not...
UndergradMajor                    What was your primary field of study?
Hobbyist                                        Do you code as a hobby?
Age1stCode            At what age did you write your first line of c...
ConvertedComp         Salary converted to annual USD salaries using ...
WebframeWorkedWith    Which web frameworks have you done extensive d...
WorkWeekHrs           On average, how many hours per week do you wor...
DatabaseWorkedWith    Which database environments have you done exte...
DevType               Which of the following describe you

In [15]:
#Check the number of rows with missing values to decide how to handle them
new_pry_df.isnull().sum()

Respondent                0
MainBranch              299
Gender                13904
Ethnicity             18513
EdLevel                7030
Age                   19015
UndergradMajor        13466
Hobbyist                 45
Age1stCode             6561
ConvertedComp         29705
WebframeWorkedWith    22182
WorkWeekHrs           23310
DatabaseWorkedWith    14924
DevType               15091
Employment              607
JobFactors            15112
LanguageWorkedWith     7083
YearsCode              6777
YearsCodePro          18112
Country                 389
dtype: int64

From the output immediately above, we can see that there are lots of missing values in the new primary dataset. In our case, we will drop all the rows with missing values.

In [16]:
#Create a newer dataset from the new primary dataset tht contains no missing values
newer_pry_df = new_pry_df.dropna()

#Check to confirm that there are no missing values in the newer primary dataset
newer_pry_df.isnull().sum()

Respondent            0
MainBranch            0
Gender                0
Ethnicity             0
EdLevel               0
Age                   0
UndergradMajor        0
Hobbyist              0
Age1stCode            0
ConvertedComp         0
WebframeWorkedWith    0
WorkWeekHrs           0
DatabaseWorkedWith    0
DevType               0
Employment            0
JobFactors            0
LanguageWorkedWith    0
YearsCode             0
YearsCodePro          0
Country               0
dtype: int64

As expected, the output immediately above shows that there are no missing values in the newer primary dataset.

In [17]:
#Check the newer primary dataset to know the number of rows involved
newer_pry_df

Respondent                      MainBranch Gender  \
7               8  I am a developer by profession    Man   
9              10  I am a developer by profession    Man   
10             11  I am a developer by profession    Man   
13             14  I am a developer by profession    Man   
15             16  I am a developer by profession    Man   
...           ...                             ...    ...   
62016       63311  I am a developer by profession    Man   
62212       63516  I am a developer by profession    Man   
63402       64810  I am a developer by profession    Man   
63517       64938  I am a developer by profession  Woman   
63955       65414  I am a developer by profession    Man   

                          Ethnicity  \
7      White or of European descent   
9      White or of European descent   
10     White or of European descent   
13     White or of European descent   
15     White or of European descent   
...                             ...   
62016  White or of European descent   
62212               Southeast Asian   
63402  White or of European descent   
63517  White or of European descent   
63955   Black or of African descent   

                                                 EdLevel   Age  \
7           Bachelor’s degree (B.A., B.S., B.Eng., etc.)  36.0   
9        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)  22.0   
10          Bachelor’s degree (B.A., B.S., B.Eng., etc.)  23.0   
13                   Associate degree (A.A., A.S., etc.)  27.0   
15          Bachelor’s degree (B.A., B.S., B.Eng., etc.)  45.0   
...                                                  ...   ...   
62016                Associate degree (A.A., A.S., etc.)  27.0   
62212       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  30.0   
63402  Some college/university study without earning ...  32.0   
63517                 Professional degree (JD, MD, etc.)  33.0   
63955    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)  22.0   

                                          UndergradMajor Hobbyist Age1stCode  \
7      Computer science, computer engineering, or sof...      Yes         12   
9                              Mathematics or statistics      Yes         14   
10     Computer science, computer engineering, or sof...      Yes         13   
13     Computer science, computer engineering, or sof...      Yes         13   
15     Computer science, computer engineering, or sof...      Yes          8   
...                                                  ...      ...        ...   
62016  Computer science, computer engineering, or sof...      Yes         16   
62212  Another engineering discipline (such as civil,...      Yes         21   
63402  Computer science, computer engineering, or sof...      Yes         12   
63517  Computer science, computer engineering, or sof...       No         13   
63955  Computer science, computer engineering, or sof...      Yes         17   

       ConvertedComp                  WebframeWorkedWith  WorkWeekHrs  \
7           116000.0                               Flask         39.0   
9            32315.0                        Flask;jQuery         36.0   
10           40070.0  Angular;Angular.js;Django;React.js         40.0   
13           66000.0                      Angular;Vue.js         40.0   
15          108576.0                     jQuery;React.js         50.0   
...              ...                                 ...          ...   
62016       109956.0                Angular;ASP.NET Core         80.0   
62212        38724.0                      ASP.NET;jQuery          9.0   
63402        74500.0  Angular;ASP.NET Core;Django;jQuery         35.0   
63517        59454.0   Django;Flask;jQuery;Ruby on Rails         40.0   
63955         9612.0      Gatsby;jQuery;Laravel;React.js         40.0   

                                      DatabaseWorkedWith  \
7                                    MariaDB;MySQL;Redis   
9                                   Microsoft SQL Server   
10    

From the table immediately above, we now have 18,241 rows (or respondent entries) and all of them are without missing values.

In [18]:
#View the statistical summary of the newer primary dataset to make useful observations
newer_pry_df.describe()

Respondent           Age  ConvertedComp   WorkWeekHrs
count  18241.000000  18241.000000   1.824100e+04  18241.000000
mean   28388.710652     31.833797   1.038853e+05     40.570651
std    18556.638953      8.089524   2.277009e+05     15.526661
min        8.000000     15.000000   0.000000e+00      1.000000
25%    12890.000000     26.000000   2.659900e+04     40.000000
50%    25474.000000     30.000000   5.467200e+04     40.000000
75%    46891.000000     36.000000   9.573600e+04     42.000000
max    65414.000000    279.000000   2.000000e+06    475.000000

From the summary immediately above, we can see that the "Age" and "WorkWeekHrs" columns need to be fixed because the maximum age observed is 279 (years) and the maximum number of hours spent on programming work per week is 475. It is unlikely for any living human to be 279 years old in this age. Likewise, it is impossible for a person to work for more than 168 hours per week, if they are ever able to work continuously without sleep or any interruption. We will therefore drop all the rows containing ages greater than 60 (years) and those containing work week hours greater than 133 for the purpose of our analysis.

In [19]:
#Ignore rows that have entry values for column "Age" greater than 60
#To clear the warning that is showing or may show after you run the code in this cell, rerun just this cell once or twice
newer_pry_df.drop(newer_pry_df[newer_pry_df.Age > 60].index, inplace=True)

C:\Users\hp\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [20]:
#Check the new statistical summary of the newer primary dataset
newer_pry_df.describe()

Respondent           Age  ConvertedComp   WorkWeekHrs
count  18158.000000  18158.000000   1.815800e+04  18158.000000
mean   28403.122425     31.661543   1.035905e+05     40.569294
std    18548.894544      7.515381   2.275053e+05     15.542892
min        8.000000     15.000000   0.000000e+00      1.000000
25%    12908.250000     26.000000   2.648700e+04     40.000000
50%    25487.500000     30.000000   5.448000e+04     40.000000
75%    46881.000000     36.000000   9.500000e+04     42.000000
max    65414.000000     60.000000   2.000000e+06    475.000000

From the output immediately above, we can see that the maximum age is now 60 (years).

In [21]:
#Ignore rows that have entry values for column "WorkWeekHrs" greater than 133
#To clear the warning that is showing or may show after you run the code in this cell, rerun just this cell once or twice
newer_pry_df.drop(newer_pry_df[newer_pry_df.WorkWeekHrs > 133].index, inplace=True)

C:\Users\hp\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [22]:
#Check the outcome of ignoring the rows with unrealistic entries for WorkWeekHrs
newer_pry_df.describe()

Respondent           Age  ConvertedComp   WorkWeekHrs
count  18107.000000  18107.000000   1.810700e+04  18107.000000
mean   28394.627106     31.663296   1.036626e+05     39.994435
std    18554.024994      7.518955   2.276448e+05      9.476259
min        8.000000     15.000000   0.000000e+00      1.000000
25%    12896.500000     26.000000   2.649600e+04     40.000000
50%    25479.000000     30.000000   5.448000e+04     40.000000
75%    46880.000000     36.000000   9.500000e+04     42.000000
max    65414.000000     60.000000   2.000000e+06    130.000000

From the output immediately above, the maximum WorkWeekHrs is now 130 which is less than the 133 that we used as a benchmark. Therefore the change has been applied.

In [23]:
#Check the total number of rows available after applying age restriction and WorkWeekHrs limitation
newer_pry_df

Respondent                      MainBranch Gender  \
7               8  I am a developer by profession    Man   
9              10  I am a developer by profession    Man   
10             11  I am a developer by profession    Man   
13             14  I am a developer by profession    Man   
15             16  I am a developer by profession    Man   
...           ...                             ...    ...   
62016       63311  I am a developer by profession    Man   
62212       63516  I am a developer by profession    Man   
63402       64810  I am a developer by profession    Man   
63517       64938  I am a developer by profession  Woman   
63955       65414  I am a developer by profession    Man   

                          Ethnicity  \
7      White or of European descent   
9      White or of European descent   
10     White or of European descent   
13     White or of European descent   
15     White or of European descent   
...                             ...   
62016  White or of European descent   
62212               Southeast Asian   
63402  White or of European descent   
63517  White or of European descent   
63955   Black or of African descent   

                                                 EdLevel   Age  \
7           Bachelor’s degree (B.A., B.S., B.Eng., etc.)  36.0   
9        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)  22.0   
10          Bachelor’s degree (B.A., B.S., B.Eng., etc.)  23.0   
13                   Associate degree (A.A., A.S., etc.)  27.0   
15          Bachelor’s degree (B.A., B.S., B.Eng., etc.)  45.0   
...                                                  ...   ...   
62016                Associate degree (A.A., A.S., etc.)  27.0   
62212       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  30.0   
63402  Some college/university study without earning ...  32.0   
63517                 Professional degree (JD, MD, etc.)  33.0   
63955    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)  22.0   

                                          UndergradMajor Hobbyist Age1stCode  \
7      Computer science, computer engineering, or sof...      Yes         12   
9                              Mathematics or statistics      Yes         14   
10     Computer science, computer engineering, or sof...      Yes         13   
13     Computer science, computer engineering, or sof...      Yes         13   
15     Computer science, computer engineering, or sof...      Yes          8   
...                                                  ...      ...        ...   
62016  Computer science, computer engineering, or sof...      Yes         16   
62212  Another engineering discipline (such as civil,...      Yes         21   
63402  Computer science, computer engineering, or sof...      Yes         12   
63517  Computer science, computer engineering, or sof...       No         13   
63955  Computer science, computer engineering, or sof...      Yes         17   

       ConvertedComp                  WebframeWorkedWith  WorkWeekHrs  \
7           116000.0                               Flask         39.0   
9            32315.0                        Flask;jQuery         36.0   
10           40070.0  Angular;Angular.js;Django;React.js         40.0   
13           66000.0                      Angular;Vue.js         40.0   
15          108576.0                     jQuery;React.js         50.0   
...              ...                                 ...          ...   
62016       109956.0                Angular;ASP.NET Core         80.0   
62212        38724.0                      ASP.NET;jQuery          9.0   
63402        74500.0  Angular;ASP.NET Core;Django;jQuery         35.0   
63517        59454.0   Django;Flask;jQuery;Ruby on Rails         40.0   
63955         9612.0      Gatsby;jQuery;Laravel;React.js         40.0   

                                      DatabaseWorkedWith  \
7                                    MariaDB;MySQL;Redis   
9                                   Microsoft SQL Server   
10    

From the table immediately above, we now have 18,107 applicable respondents.
However, the "LanguageWorkedWith" column contains multiple values which we would like to seperate and properly analyze. So, we will work on splitting that column.

In [24]:
#Check the detailed meaning of the LanguageWorkedWith column title
new_sec_df.LanguageWorkedWith

'Which programming, scripting, and markup languages have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row.)'

In [25]:
#Check summary of the types of programming languages worked with and those to be worked within the past or coming year 
print(newer_pry_df['LanguageWorkedWith'].value_counts())

C#;HTML/CSS;JavaScript;SQL                                     446
C#;HTML/CSS;JavaScript;SQL;TypeScript                          421
HTML/CSS;JavaScript;PHP;SQL                                    391
HTML/CSS;JavaScript;TypeScript                                 239
Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;SQL;TypeScript    219
                                                              ... 
C#;HTML/CSS;JavaScript;Ruby                                      1
Dart;Java;JavaScript;Python;SQL                                  1
C#;C++;HTML/CSS;Java;JavaScript;PHP;Python;R;SQL                 1
C;C++;JavaScript;PHP;Python;R;SQL                                1
Assembly;C;C++;HTML/CSS;Java;JavaScript;PHP;Python;Ruby;SQL      1
Name: LanguageWorkedWith, Length: 5934, dtype: int64


Unfortunately, we cannot ascertain the actual number of unique programming languages involved from the summary immediately above. So, we will create a function that will help us split the LanguageWorkedWith column and let us know how many unique programming languages were selected.

In [26]:
#Create a function that turns a column containing a list of values into a DataFrame with one column for each possible option
def split_multicolumn(col_series):
    result_df = col_series.to_frame()
    options = []
    #Iterate over the column
    for idx, value in col_series[col_series.notnull()].iteritems():
        #Break each value into a list of options
        for option in value.split(';'):
            #Add the option as a column to result
            if not option in result_df.columns:
                options.append(option)
                result_df[option] = False
            #Mark the value in the option column as True
            result_df.at[idx, option] = True
    return result_df[options]

In [27]:
#Create a new DataFrame from the newer_pry_df DataFrame by applying the new function that was created to newer_pry_df
LanguageWorkedWith_df = split_multicolumn(newer_pry_df.LanguageWorkedWith)

In [28]:
#View the resulting DataFrame you have just created
LanguageWorkedWith_df

Python    SQL  HTML/CSS   Java  JavaScript     C#  Swift  TypeScript  \
7        True   True     False  False       False  False  False       False   
9        True   True      True   True        True  False  False       False   
10      False  False     False  False        True   True   True       False   
13      False   True      True  False        True  False  False        True   
15      False  False      True   True        True  False  False       False   
...       ...    ...       ...    ...         ...    ...    ...         ...   
62016   False   True      True  False        True   True  False        True   
62212   False   True      True  False        True   True  False       False   
63402    True   True      True  False        True   True  False        True   
63517    True   True      True   True        True  False  False       False   
63955   False   True      True  False        True  False  False       False   

       Bash/Shell/PowerShell  Kotlin  ...      C    C++  Scala    PHP   Perl  \
7                      False   False  ...  False  False  False  False  False   
9                      False   False  ...  False  False  False  False  False   
10                     False   False  ...  False  False  False  False  False   
13                     False   False  ...  False  False  False  False  False   
15                      True    True  ...  False  False  False  False  False   
...                      ...     ...  ...    ...    ...    ...    ...    ...   
62016                  False   False  ...  False  False  False  False  False   
62212                  False   False  ...  False  False  False  False  False   
63402                   True   False  ...  False  False  False  False  False   
63517                  False   False  ...   True   True  False   True  False   
63955                  False   False  ...  False  False  False   True  False   

       Assembly  Objective-C   Dart  Haskell  Julia  
7         False        False  False    False  False  
9         False        False  False    False  False  
10        False        False  False    False  False  
13        False        False  False    False  False  
15        False        False  False    False  False  
...         ...          ...    ...      ...    ...  
62016     False        False  False    False  False  
62212     False        False  False    False  False  
63402     False        False  False    False  False  
63517      True        False  False    False  False  
63955     False        False  False    False  False  

[18107 rows x 25 columns]

In the table immediately above (LangauageWorkedWith_df) which contains all the unique entries under the LanguageWorkedWith column of the newer_pry_df DataFrame, there is one column for each programming language. If a respondent (surveyed programmer) has indicated that they have worked with a particular programming language, the corresponding column value is True. Otherwise, it is False.

We can also see from the table immediately above that the respondents have worked with 25 programming languages in all.

In [29]:
#Check the usage distribution of the 25 programming langaguages among the 18,107 respondents involved in our analysis
Total_LanguageWorkedWith = LanguageWorkedWith_df.sum().sort_values(ascending=False)
Total_LanguageWorkedWith

JavaScript               15121
HTML/CSS                 13362
SQL                      12118
Python                    7564
Java                      7147
Bash/Shell/PowerShell     7071
C#                        6848
TypeScript                6787
PHP                       5142
C++                       2809
C                         2399
Go                        1903
Ruby                      1805
Kotlin                    1411
VBA                       1039
Swift                      865
Rust                       807
R                          807
Scala                      779
Assembly                   644
Dart                       608
Objective-C                595
Perl                       538
Haskell                    284
Julia                       90
dtype: int64

Now that we have cleaned our data, we can proceed to report generation using Pandas Profiling

##### Step C : Report Generation

In [30]:
#Connect to the internet and install Pandas Profiling for report generation if you haven't done so already
#The code below was ashed out intetionally. Please remove the ash in the code to run it if you need to
#!pip install pandas-profiling --user

Pandas has been installed already. Please note that you may have to restart the kernel and rerun the whole notebook after installing, especially if you keep receiving an error when trying to import ProfileReport after installing Profiling already.

In [31]:
#Import pandas profiling
from pandas_profiling import ProfileReport

In [32]:
#Generate the report
newer_pry_df.profile_report()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [34]:
#To save a copy of the report in HTML version, first create 
profile_report = newer_pry_df.profile_report()

#Generate the HTML copy with a suitable name
#After exportation, the generated HTML file will be available in the same folder
#Where this particular Jupyter Notebook is located or being saved on your PC
profile_report.to_file("PremierProjectAnalysis.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

### End of Exploratory Data Analysis. Next is Data Visualization.